spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_cdc?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS
